# Modules

A **module** that contains functions and statements. You can import modules by using the **import** statement. This will save you tons of time and coding space because you will not have to create these functions yourself. If you are coming from a different language, you may know modules as **packages**. However, packages have a slightly different meaning in python. For an explanation on the difference, visit this website http://knowpapa.com/modpaclib-py/. 

Let's look at a very useful package - the **math** package. Let's go ahead and import this package.

In [1]:
#import math package
import math

Now that we have imported the math package, we have access to all of the functions that come with it. In order to use these functions, we simply do **math.function()**. For example, if I want to use the square root function, I just do **math.sqrt()**

In [5]:
#sqrt
math.sqrt(25)

5.0

We can use the **dir()** function to output all of the functions in a package.

In [7]:
#Get all of the functions in the math package
dir(math)

['__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'pi',
 'pow',
 'radians',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc']

In your code, you may not use many of the functions in the package, but only need one or two. In order to decrease the runtime of your code, it may be a good idea to only import the functions you need, rather than the whole package. To do this we can use the **from** statement along with the **import** statement. The syntax is as follows:

**from** module **import** function

If you do this, you will not have to specify the module from which the function came from when calling the function.

Let's see how we can import only the array function from the **numpy** package - another very useful package.

In [10]:
#import array function from numpy package
from numpy import array

In [12]:
#use function to create an array
a = array([[1,2,3], [4,5,6], [7,8,9]])

In [14]:
#check if it worked
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


We can also us the **as** statment in order to refer to a package with a different name. We will do this to refer to the **numpy** package as **np** (this is very common when importing the numpy package).

In [18]:
#import the numpy package and have the reference name be np
import numpy as np

In [19]:
#call on log10 function from numpy (np)
np.log10(1000)

3.0

## Installing Modules 

If you require a module and you do not already have it installed (importing does not work because there is no existing module on your computer to be imported), than you can install it through the terminal (Mac) or command prompt (Windows) using **pip**. The syntax is:

    pip install module_name